import Navibar from "@/components/Navibar";
import "./globals.css";
import { Inter, Raleway } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Stuxis öppna förskola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navibar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
